# Generated by Django 5.2 on 2025-06-04 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Produk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=200, verbose_name="Nama Produk")),
                ("deskripsi", models.TextField(verbose_name="Deskripsi")),
                (
                    "harga",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Harga"
                    ),
                ),
                (
                    "kategori",
                    models.CharField(
                        choices=[
                            ("indoor", "Tanaman Indoor"),
                            ("outdoor", "Tanaman Outdoor"),
                            ("kaktus", "Kaktus & Sukulen"),
                        ],
                        max_length=20,
                        verbose_name="Kategori",
                    ),
                ),
                ("perawatan", models.TextField(verbose_name="Cara Perawatan")),
                ("stok", models.PositiveIntegerField(default=0, verbose_name="Stok")),
                (
                    "gambar_url",
                    models.URLField(
                        blank=True,
                        help_text="Link gambar dari Unsplash atau sumber lain",
                        null=True,
                        verbose_name="URL Gambar",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Dibuat pada"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Diupdate pada"),
                ),
            ],
            options={
                "verbose_name": "Produk",
                "verbose_name_plural": "Produk",
                "ordering": ["-created_at"],
            },
        ),
    ]
