# Generated by Django 5.2 on 2025-06-04 07:57

import produk.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produk", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="produk",
            name="gambar",
            field=models.ImageField(
                blank=True,
                help_text="Upload gambar produk (opsional)",
                null=True,
                upload_to=produk.models.produk_image_path,
                verbose_name="Upload Gambar",
            ),
        ),
        migrations.AlterField(
            model_name="produk",
            name="gambar_url",
            field=models.URLField(
                blank=True,
                help_text="Link gambar dari Unsplash atau sumber lain (opsional)",
                null=True,
                verbose_name="URL Gambar",
            ),
        ),
    ]
